#!/usr/bin/env node
// Copy the vendored Pyodide runtime assets from node_modules into
// web/public/pyodide so loadPyodide({ indexURL: "/pyodide/" }) can fetch them
// at runtime. Mirrors scripts/sync-wasm.mjs (which serves the kernel from
// /wasm/). These files are large (~14 MB) and reproducible, so public/pyodide
// is git-ignored and regenerated by the predev/prebuild hooks instead of
// committed. Run gated on the pyodide package version staying in sync.
import { copyFileSync, existsSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const pyodideDir = dirname(require.resolve("pyodide/package.json"));
const outDir = resolve(scriptDir, "../public/pyodide");

// The exact set loadPyodide fetches from indexURL for a pure-Python run.
const ASSETS = ["pyodide.asm.js", "pyodide.asm.wasm", "python_stdlib.zip", "pyodide-lock.json"];

mkdirSync(outDir, { recursive: true });
let copied = 0;
for (const asset of ASSETS) {
  const source = join(pyodideDir, asset);
  if (!existsSync(source)) {
    throw new Error(`Missing pyodide asset: ${source}`);
  }
  copyFileSync(source, join(outDir, asset));
  copied += 1;
}
console.log(`copied ${copied} pyodide assets into ${outDir}`);
