file(MAKE_DIRECTORY "${REPLAY_DIR}")
set(replay_path "${REPLAY_DIR}/preset_duel_python_v0.replay.json")
file(REMOVE "${replay_path}")

execute_process(
  COMMAND "${ROBOLOCKS_CLI}" run
    --battle "${ROBOLOCKS_SOURCE_DIR}/fixtures/matches/preset_duel_python_v0.json"
    --ticks 100
    --replay-out "${replay_path}"
  RESULT_VARIABLE result
  OUTPUT_VARIABLE output
  ERROR_VARIABLE error
)

if(NOT result EQUAL 0)
  message(FATAL_ERROR "replay command failed with ${result}: ${error}")
endif()

if(NOT EXISTS "${replay_path}")
  message(FATAL_ERROR "expected replay file to be written: ${replay_path}")
endif()

file(READ "${replay_path}" replay_json)
string(JSON replay_type GET "${replay_json}" type)
string(JSON tick_rate GET "${replay_json}" tickRate)
string(JSON obstacle_count LENGTH "${replay_json}" obstacles)
string(JSON first_obstacle_id GET "${replay_json}" obstacles 0 id)
string(JSON frame_count LENGTH "${replay_json}" frames)
string(JSON first_tick GET "${replay_json}" frames 0 tick)
string(JSON final_tick GET "${replay_json}" frames 100 tick)
string(JSON mid_blue_x GET "${replay_json}" frames 80 units 0 position x)
string(JSON mid_blue_y GET "${replay_json}" frames 80 units 0 position y)
string(FIND "${replay_json}" "\"unitId\":1,\"type\":\"aimAt\"" blue_aim_action)
string(FIND "${replay_json}" "\"unitId\":1,\"type\":\"fireIfSolution\"" blue_fire_action)
string(FIND "${replay_json}" "\"unitId\":2,\"type\":\"moveTo\"" red_move_action)
string(FIND "${replay_json}" "\"intents\":{\"mobility\"" unit_intents)
string(FIND "${replay_json}" "\"remainingMeters\"" mobility_remaining)
string(FIND "${replay_json}" "\"errorDegrees\"" angular_error)
string(FIND "${replay_json}" "\"weaponCooldownTicks\"" weapon_cooldown)
string(FIND "${replay_json}" "\"code\":\"armor_bounced\"" armor_bounced)
string(FIND "${replay_json}" "Projectile failed to penetrate front armor." armor_bounce_message)
string(FIND "${replay_json}" "\"payload\":{" event_payload)
string(FIND "${replay_json}" "\"damageType\":\"direct\"" event_damage_type)
string(FIND "${replay_json}" "\"penetrationMillimeters\":80" event_penetration_payload)
string(FIND "${replay_json}" "\"modules\":{\"mobility\":{\"id\":\"tracked_chassis_mk1\"" module_ids)
string(FIND "${replay_json}" "\"maxSpeedMetersPerSecond\":6" mobility_spec)
string(FIND "${replay_json}" "\"fireMode\":\"direct\"" weapon_fire_mode_spec)
string(FIND "${replay_json}" "\"reloadTicks\":90" weapon_spec)
string(FIND "${replay_json}" "\"penetrationMillimeters\":80" weapon_penetration_spec)
string(FIND "${replay_json}" "\"muzzleVelocityMetersPerSecond\":20" weapon_projectile_spec)
string(FIND "${replay_json}" "\"heightMeters\":" projectile_height)
string(FIND "${replay_json}" "\"frontMillimeters\":100" armor_front_spec)
string(FIND "${replay_json}" "\"projectiles\":" projectiles_field)

if(NOT replay_type STREQUAL "robolocks.replay.v1")
  message(FATAL_ERROR "unexpected replay type: ${replay_type}")
endif()
if(NOT tick_rate EQUAL 30)
  message(FATAL_ERROR "expected tickRate 30, got ${tick_rate}")
endif()
if(NOT obstacle_count EQUAL 1)
  message(FATAL_ERROR "expected 1 replay obstacle, got ${obstacle_count}")
endif()
if(NOT first_obstacle_id STREQUAL "north_cover")
  message(FATAL_ERROR "expected first replay obstacle north_cover, got ${first_obstacle_id}")
endif()
if(NOT frame_count EQUAL 101)
  message(FATAL_ERROR "expected 101 frames, got ${frame_count}")
endif()
if(NOT first_tick EQUAL 0)
  message(FATAL_ERROR "expected first tick 0, got ${first_tick}")
endif()
if(NOT final_tick EQUAL 100)
  message(FATAL_ERROR "expected final tick 100, got ${final_tick}")
endif()
if(NOT mid_blue_x GREATER 9)
  message(FATAL_ERROR "expected python bot replay to move blue away from spawn, got frame 80 blue x ${mid_blue_x}")
endif()
if(NOT mid_blue_y GREATER 7)
  message(FATAL_ERROR "expected python bot replay to show vertical movement, got frame 80 blue y ${mid_blue_y}")
endif()
if(blue_aim_action EQUAL -1)
  message(FATAL_ERROR "expected blue python bot to aim at contact")
endif()
if(blue_fire_action EQUAL -1)
  message(FATAL_ERROR "expected blue python bot to request fire solution")
endif()
if(red_move_action EQUAL -1)
  message(FATAL_ERROR "expected red python bot to move tactically")
endif()
if(unit_intents EQUAL -1)
  message(FATAL_ERROR "expected replay units to include intent dashboard state")
endif()
if(mobility_remaining EQUAL -1)
  message(FATAL_ERROR "expected replay mobility intent to include remaining distance")
endif()
if(angular_error EQUAL -1)
  message(FATAL_ERROR "expected replay angular intents to include error degrees")
endif()
if(weapon_cooldown EQUAL -1)
  message(FATAL_ERROR "expected replay units to include weapon cooldown ticks")
endif()
if(armor_bounced EQUAL -1)
  message(FATAL_ERROR "expected replay to include armor bounce events")
endif()
if(armor_bounce_message EQUAL -1)
  message(FATAL_ERROR "expected armor event to include facing penetration context")
endif()
if(event_payload EQUAL -1)
  message(FATAL_ERROR "expected replay events to include structured payload")
endif()
if(event_damage_type EQUAL -1)
  message(FATAL_ERROR "expected replay event payload to include damage type")
endif()
if(event_penetration_payload EQUAL -1)
  message(FATAL_ERROR "expected replay event payload to include penetration")
endif()
if(module_ids EQUAL -1)
  message(FATAL_ERROR "expected replay units to include resolved module ids")
endif()
if(mobility_spec EQUAL -1)
  message(FATAL_ERROR "expected replay units to include resolved mobility specs")
endif()
if(weapon_spec EQUAL -1)
  message(FATAL_ERROR "expected replay units to include resolved weapon specs")
endif()
if(weapon_fire_mode_spec EQUAL -1)
  message(FATAL_ERROR "expected replay units to include resolved weapon fire mode specs")
endif()
if(weapon_penetration_spec EQUAL -1)
  message(FATAL_ERROR "expected replay units to include resolved penetration specs")
endif()
if(weapon_projectile_spec EQUAL -1)
  message(FATAL_ERROR "expected replay units to include resolved projectile weapon specs")
endif()
if(projectile_height EQUAL -1)
  message(FATAL_ERROR "expected replay projectile state to include height")
endif()
if(armor_front_spec EQUAL -1)
  message(FATAL_ERROR "expected replay units to include resolved armor facing specs")
endif()
if(projectiles_field EQUAL -1)
  message(FATAL_ERROR "expected replay frames to include projectile state")
endif()
