#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void* RobolocksBattleRuntimeHandle;

RobolocksBattleRuntimeHandle robolocks_battle_runtime_create_preset_duel(void);
void robolocks_battle_runtime_destroy(RobolocksBattleRuntimeHandle handle);

void robolocks_battle_runtime_step(RobolocksBattleRuntimeHandle handle);
void robolocks_battle_runtime_run_ticks(RobolocksBattleRuntimeHandle handle, uint64_t tick_count);

uint64_t robolocks_battle_runtime_tick(RobolocksBattleRuntimeHandle handle);
size_t robolocks_battle_runtime_unit_count(RobolocksBattleRuntimeHandle handle);
uint32_t robolocks_battle_runtime_unit_id(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_x(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_y(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_hull_heading_deg(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_turret_heading_deg(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_armor(RobolocksBattleRuntimeHandle handle, size_t unit_index);
uint64_t robolocks_battle_runtime_unit_weapon_cooldown_ticks(RobolocksBattleRuntimeHandle handle, size_t unit_index);
int robolocks_battle_runtime_unit_body_shape_type(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_body_radius_m(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_body_length_m(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_body_width_m(RobolocksBattleRuntimeHandle handle, size_t unit_index);
int robolocks_battle_runtime_unit_mobility_intent_active(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_mobility_intent_target_x(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_mobility_intent_target_y(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_mobility_intent_remaining_m(RobolocksBattleRuntimeHandle handle, size_t unit_index);
uint64_t robolocks_battle_runtime_unit_mobility_intent_age_ticks(RobolocksBattleRuntimeHandle handle, size_t unit_index);
int robolocks_battle_runtime_unit_turret_intent_active(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_turret_intent_target_x(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_turret_intent_target_y(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_turret_intent_error_deg(RobolocksBattleRuntimeHandle handle, size_t unit_index);
uint64_t robolocks_battle_runtime_unit_turret_intent_age_ticks(RobolocksBattleRuntimeHandle handle, size_t unit_index);
int robolocks_battle_runtime_unit_hull_intent_active(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_hull_intent_target_x(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_hull_intent_target_y(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_hull_intent_error_deg(RobolocksBattleRuntimeHandle handle, size_t unit_index);
uint64_t robolocks_battle_runtime_unit_hull_intent_age_ticks(RobolocksBattleRuntimeHandle handle, size_t unit_index);
int robolocks_battle_runtime_unit_weapon_intent_active(RobolocksBattleRuntimeHandle handle, size_t unit_index);
double robolocks_battle_runtime_unit_weapon_intent_min_hit_chance(RobolocksBattleRuntimeHandle handle, size_t unit_index);
uint64_t robolocks_battle_runtime_unit_weapon_intent_age_ticks(RobolocksBattleRuntimeHandle handle, size_t unit_index);
size_t robolocks_battle_runtime_obstacle_count(RobolocksBattleRuntimeHandle handle);
const char* robolocks_battle_runtime_obstacle_id(RobolocksBattleRuntimeHandle handle, size_t obstacle_index);
double robolocks_battle_runtime_obstacle_x(RobolocksBattleRuntimeHandle handle, size_t obstacle_index);
double robolocks_battle_runtime_obstacle_y(RobolocksBattleRuntimeHandle handle, size_t obstacle_index);
double robolocks_battle_runtime_obstacle_radius_m(RobolocksBattleRuntimeHandle handle, size_t obstacle_index);
int robolocks_battle_runtime_obstacle_blocks_movement(RobolocksBattleRuntimeHandle handle, size_t obstacle_index);
int robolocks_battle_runtime_obstacle_blocks_line_of_sight(RobolocksBattleRuntimeHandle handle, size_t obstacle_index);
size_t robolocks_battle_runtime_event_count(RobolocksBattleRuntimeHandle handle);
uint64_t robolocks_battle_runtime_event_tick(RobolocksBattleRuntimeHandle handle, size_t event_index);
uint32_t robolocks_battle_runtime_event_unit_id(RobolocksBattleRuntimeHandle handle, size_t event_index);
const char* robolocks_battle_runtime_event_code(RobolocksBattleRuntimeHandle handle, size_t event_index);
const char* robolocks_battle_runtime_event_message(RobolocksBattleRuntimeHandle handle, size_t event_index);
size_t robolocks_battle_runtime_projectile_count(RobolocksBattleRuntimeHandle handle);
uint64_t robolocks_battle_runtime_projectile_id(RobolocksBattleRuntimeHandle handle, size_t projectile_index);
uint32_t robolocks_battle_runtime_projectile_owner_unit_id(RobolocksBattleRuntimeHandle handle, size_t projectile_index);
double robolocks_battle_runtime_projectile_previous_x(RobolocksBattleRuntimeHandle handle, size_t projectile_index);
double robolocks_battle_runtime_projectile_previous_y(RobolocksBattleRuntimeHandle handle, size_t projectile_index);
double robolocks_battle_runtime_projectile_x(RobolocksBattleRuntimeHandle handle, size_t projectile_index);
double robolocks_battle_runtime_projectile_y(RobolocksBattleRuntimeHandle handle, size_t projectile_index);
double robolocks_battle_runtime_projectile_radius_m(RobolocksBattleRuntimeHandle handle, size_t projectile_index);
size_t robolocks_battle_runtime_action_count(RobolocksBattleRuntimeHandle handle);
uint32_t robolocks_battle_runtime_action_unit_id(RobolocksBattleRuntimeHandle handle, size_t action_index);
const char* robolocks_battle_runtime_action_type(RobolocksBattleRuntimeHandle handle, size_t action_index);
const char* robolocks_battle_runtime_action_channel(RobolocksBattleRuntimeHandle handle, size_t action_index);
int robolocks_battle_runtime_action_has_position(RobolocksBattleRuntimeHandle handle, size_t action_index);
double robolocks_battle_runtime_action_position_x(RobolocksBattleRuntimeHandle handle, size_t action_index);
double robolocks_battle_runtime_action_position_y(RobolocksBattleRuntimeHandle handle, size_t action_index);
int robolocks_battle_runtime_action_has_target(RobolocksBattleRuntimeHandle handle, size_t action_index);
double robolocks_battle_runtime_action_target_x(RobolocksBattleRuntimeHandle handle, size_t action_index);
double robolocks_battle_runtime_action_target_y(RobolocksBattleRuntimeHandle handle, size_t action_index);
int robolocks_battle_runtime_action_has_min_hit_chance(RobolocksBattleRuntimeHandle handle, size_t action_index);
double robolocks_battle_runtime_action_min_hit_chance(RobolocksBattleRuntimeHandle handle, size_t action_index);
int robolocks_battle_runtime_action_has_scan_arc(RobolocksBattleRuntimeHandle handle, size_t action_index);
double robolocks_battle_runtime_action_center_deg(RobolocksBattleRuntimeHandle handle, size_t action_index);
double robolocks_battle_runtime_action_width_deg(RobolocksBattleRuntimeHandle handle, size_t action_index);

#ifdef __cplusplus
}
#endif
